/* JDE Inventory Counts - Target */
SELECT
MCHB.WERKS as `Plant (WERKS)`
,MCHB.MATNR as `Material (MATNR)`
,MCHB.LGORT `Stor. Loc. (LGORT)`
,MCHB.CHARG `Batch (CHARG)`
,SUM(MCHB.CLABS) as `Unrestricted (CLABS)`
,MCH1.ZUSTD `Batch restr. (ZUSTD)`
,VB.HARD_ORD_QTY as `SO Hard Commit Qty`
,VB.SOFT_ORD_QTY as `SO Soft Commit Qty`
--,VB.FUTURE_COMMIT as `SO Future Commit Qty`
,RE.RESV_HARD_QTY as `Production Order Resv. Hard Commit Qty`
,RE.RESV_SOFT_QTY as `Production Order Resv. Soft Commit Qty`

FROM dev_hmd.NSDM_V_MCHB MCHB

  LEFT OUTER JOIN dev_hmd.MCH1 ON MCHB.CHARG = MCH1.CHARG AND MCHB.MATNR = MCH1.MATNR AND MCH1.MANDT = MCHB.MANDT

LEFT JOIN (SELECT VB.MANDT, VB.MATNR, VB.WERKS,
									SUM(CASE WHEN (VBB.BMENG) > 0 THEN VBB.BMENG  ELSE 0 END) HARD_ORD_QTY,
									SUM(CASE WHEN (VBB.WMENG - VBB.BMENG) <> 0 THEN VBB.WMENG - VBB.BMENG ELSE 0 END) SOFT_ORD_QTY,
									SUM(VBB2.FUTURE_COMMIT) FUTURE_COMMIT
              FROM dev_hmd.VBAK VK
									LEFT JOIN dev_hmd.VBAP VB ON VK.VBELN = VB.VBELN AND VB.GBSTA IN ('A', 'B') AND VB.MANDT = VK.MANDT
									LEFT JOIN (SELECT VBB.VBELN,VBB.POSNR,VBB.MANDT, SUM(VBB.WMENG) WMENG, SUM(VBB.BMENG) BMENG, max(VBB.EDATU) EDATU
															FROM dev_hmd.VBEP VBB
															WHERE TO_DATE(VBB.EDATU, "yyyyMMdd") < CURRENT_DATE()+7
															GROUP BY 1,2,3
															) VBB
													ON VB.VBELN = VBB.VBELN AND VB.POSNR = VBB.POSNR AND VK.MANDT = VBB.MANDT
									LEFT JOIN (SELECT VBB.VBELN,VBB.POSNR,VBB.MANDT, SUM(VBB.BMENG) FUTURE_COMMIT
															FROM dev_hmd.VBEP VBB
															WHERE TO_DATE(VBB.EDATU, "yyyyMMdd") > CURRENT_DATE()+7
															AND BMENG > 0
															GROUP BY 1,2,3
														) VBB2
													ON VB.VBELN = VBB2.VBELN AND VB.POSNR = VBB2.POSNR  AND VK.MANDT = VBB2.MANDT
		    GROUP BY 1,2,3) VB
    ON MCHB.MATNR = VB.MATNR AND MCHB.WERKS = VB.WERKS AND MCHB.MANDT = VB.MANDT

LEFT JOIN (SELECT RE.MANDT, RE.MATNR, RE.WERKS, SUM(CASE WHEN RE.LGORT IS NOT NULL THEN RE.BDMNG - RE.ENMNG ELSE 0 END) as RESV_HARD_QTY, SUM(CASE WHEN RE.LGORT IS NULL THEN RE.BDMNG - RE.ENMNG ELSE 0 END) as RESV_SOFT_QTY 
							FROM dev_hmd.RESB RE
							WHERE RE.XLOEK IS NULL
							AND RE.KZEAR IS NULL
                            AND RE.BWART = '261'
							GROUP BY 1,2,3) RE
							ON MCHB.MATNR  = RE.MATNR AND MCHB.WERKS = RE.WERKS  AND  MCHB.MANDT = RE.MANDT

WHERE MCHB.MANDT = '100'
AND MCHB.WERKS = 'USI4'
AND MCHB.MATNR = '310005'
GROUP BY 1,2,3,4,6,7,8,9,10