/* WO Performance */
SELECT
AFKO.AUFNR `Order (AUFNR)`
,AUFK.AUART `Order Type (AUART)`
,AFPO.MATNR `Material (MATNR)`
,AFPO.CHARG `Batch (CHARG)`
,AFKO.DISPO `MRP controller (DISPO)`
,AFKO.FEVOR `Prodn Supervisor (FEVOR)`
,AFPO.DWERK `Plant (WERKS)`
,AFVC.VORNR `Activity (VORNR)`
,CRHD.ARBPL `Work Center (ARBPL)`
,CRTX.KTEXT `Description (KTEXT)`
,AFVC.ARBID `Object ID (ARBID)`
,AFVC.LTXA1 `Op. Short Text (LTXA1)`
,AFVV.SSAVD `Latest start (SSAVD)`
,AFVV.SSAVZ `Lat. start time (SSAVZ)`
,AFVV.IEBD `Processing End Date (IEBD)`
,AFVV.IEBZ `Processing End Time (IEBZ)`
,AFVV.MGVRG `Operation Qty (MGVRG)`
,AFVV.LMNGA `Confirmed Yield (LMNGA)`
,100 - AFVC.AUFAK  `100 - Scrap Percentage to get Confirmed Yield %`
,AFVV.VGW03 `Standard Value (VGW03)`
,AFVV.VGW01 `Standard Value (VGW01)`
,AFVV.VGW02 `Standard Value (VGW02)`
,AFVV.ZWNOR `Std Queue Time (ZWNOR)`
,AFVV.ZTNOR `Std Move Time (ZTNOR)`
,MARC.WZEIT `Total RL time (WZEIT)`
,AFVV.ISM03 `Conf. Activity (ISM03)`
,AFVV.ISM01 `Conf. Activity (ISM01)`
,AFVV.ISM02 `Conf. Activity (ISM02)`
,AFVV.WARTZ `Queue Time (WARTZ)`
,AFVV.TRANZ `Move Time (TRANZ)`
,AFVV.SSAVD || AFVV.SSAVZ `Latest start + Lat. start time (SSAVD + SSAVZ)`
FROM dev_hm2.AUFK
  LEFT OUTER JOIN dev_hm2.AFKO ON AUFK.AUFNR = AFKO.AUFNR  AND AFKO.MANDT = AUFK.MANDT
  LEFT OUTER JOIN dev_hm2.AFPO ON AFKO.AUFNR = AFPO.AUFNR  AND AFPO.MANDT = AUFK.MANDT
  LEFT OUTER JOIN dev_hm2.AFVC ON AFKO.AUFPL = AFVC.AUFPL  AND AFVC.MANDT = AUFK.MANDT
  LEFT OUTER JOIN dev_hm2.AFVV ON AFVC.AUFPL = AFVV.AUFPL  AND AFVC.APLZL = AFVV.APLZL  AND AFVV.MANDT = AUFK.MANDT
  LEFT OUTER JOIN dev_hm2.CRHD ON AFVC.ARBID = CRHD.OBJID  AND AFVC.WERKS = CRHD.WERKS  AND CRHD.MANDT = AUFK.MANDT
  LEFT OUTER JOIN dev_hm2.CRTX ON CRHD.OBJTY = CRTX.OBJTY  AND CRHD.OBJID = CRTX.OBJID  AND CRTX.SPRAS = 'E'  AND CRTX.MANDT = AUFK.MANDT
  LEFT OUTER JOIN dev_hm2.MARC ON AFPO.DWERK = MARC.WERKS  AND AFPO.MATNR = MARC.MATNR  AND MARC.MANDT = AUFK.MANDT

WHERE  AUFK.MANDT = '500'
--AND AUFK.AUFNR = '002000001644'
--AND AUSP.ATWRT  IS NOT NULL